restapi/src/main/java/org/cristalise/restapi/ItemUtils.java
restapi/src/main/java/org/cristalise/restapi/RestHandler.java

Configurable log level to adjust log errors related to decryption and web application exceptions.

Issue #8 - restapi reduced log errors.

---

kernel/src/main/java/org/cristalise/kernel/collection/AggregationMember.java
kernel/src/main/java/org/cristalise/kernel/collection/Dependency.java
kernel/src/main/java/org/cristalise/kernel/collection/DependencyMember.java
kernel/src/main/resources/mapFiles/CollectionMap.xml
kernel/src/test/java/org/cristalise/kernel/test/persistency/CastorXMLTest.java

Added fix on Dependency.java when updating a member collection with null (mClassProps) instance variable

#173: Fixed issue on update member collection

---

kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/predefined/CreateNewCollectionVersion.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/predefined/RemoveSlotFromCollection.java

Injected a new property ('member' field) in RemoveSlotFromCollection
Related to issue https://github.com/TitusTech/hmws/issues/274

#201: Injected 'member' prop in RemoveSlotFromCollection

---

dsl/src/main/groovy/org/cristalise/dsl/persistency/outcome/DynamicForms.groovy
dsl/src/main/groovy/org/cristalise/dsl/persistency/outcome/SchemaDelegate.groovy
dsl/src/main/groovy/org/cristalise/dsl/persistency/outcome/Struct.groovy
dsl/src/test/groovy/org/cristalise/dsl/test/persistency/outcome/SchemaBuilderDynymicFormsSpecs.groovy
xpath-outcome-initiator/src/main/java/org/cristalise/kernel/persistency/outcomebuilder/AppInfoUtils.java
xpath-outcome-initiator/src/main/java/org/cristalise/kernel/persistency/outcomebuilder/DataRecord.java
xpath-outcome-initiator/src/main/java/org/cristalise/kernel/persistency/outcomebuilder/field/StringField.java
xpath-outcome-initiator/src/test/data/outcomeBuilder/DynamicFormsWidthConfiguration.json
xpath-outcome-initiator/src/test/data/outcomeBuilder/DynamicFormsWidthConfiguration.xsd
xpath-outcome-initiator/src/test/java/org/cristalise/kernel/test/persistency/outcomebuilder/NgDynamicFormsTest.java

Issue: https://github.com/cristal-ise/cristal-ise/issues/216
Based on: https://github.com/TitusTech/webui-lib/issues/463
Results: https://github.com/TitusTech/webui-lib/issues/463#issuecomment-494223732

#216: Allowed the schema struct to define the form width

---

kernel/src/main/java/org/cristalise/kernel/scripting/Script.java

Changed log level of default script parameters check to DEBUG.

#329: Changed log level for default input/output parameters

---

docs/IDL.md
docs/_Sidebar.md
docs/index.md

Added on guide on how to compile IDL file on cristal

Cristal-ISe IDL Technical Guide

---

dsl/src/main/groovy/org/cristalise/dsl/lifecycle/instance/BlockDelegate.groovy
dsl/src/main/groovy/org/cristalise/dsl/test/builders/AgentTestBuilder.groovy
dsl/src/test/groovy/org/cristalise/dsl/test/lifecycle/instance/WFBuilderPropertySpecs.groovy
jooqdb/src/main/java/org/cristalise/storage/jooqdb/JooqClusterStorage.java
jooqdb/src/main/java/org/cristalise/storage/jooqdb/clusterStore/JooqHistoryHandler.java
jooqdb/src/main/java/org/cristalise/storage/jooqdb/clusterStore/JooqJobHandler.java
jooqdb/src/test/java/org/cristalise/storage/jooqdb/JooqHistoryTest.java
kernel/src/main/java/org/cristalise/kernel/persistency/ClusterStorage.java
kernel/src/main/java/org/cristalise/kernel/persistency/ClusterStorageManager.java
kernel/src/main/java/org/cristalise/kernel/persistency/RemoteMap.java
kernel/src/main/java/org/cristalise/kernel/persistency/TransactionManager.java
kernel/src/main/java/org/cristalise/storage/MemoryOnlyClusterStorage.java
kernel/src/main/java/org/cristalise/storage/ProxyLoader.java
kernel/src/main/java/org/cristalise/storage/XMLClusterStorage.java
kernel/src/test/java/org/cristalise/kernel/test/persistency/XMLClusterStorageTest.java
lookup-ldap/src/main/java/org/cristalise/lookup/ldap/LDAPClusterStorage.java
testing/src/main/groovy/org/cristalise/kernel/test/lifecycle/instance/AdvancementCalculatorTest.groovy
xmldb/src/main/java/org/cristalise/storage/xmldb/XMLDBClusterStorage.java

Fixes https://github.com/cristal-ise/cristal-ise/issues/84

#84: Query the database for the last id

---

kernel/src/main/java/org/cristalise/kernel/utils/DescriptionObjectCache.java

#447 Deadlock caused by editing a Script

---

jooqdb/pom.xml
pom.xml
testing/pom.xml

#497 update mysql dependency to 8.0.25

---

kernel/src/main/java/org/cristalise/kernel/scripting/Script.java
testing/src/main/groovy/org/cristalise/restapi/test/ConcurrentTest.groovy

Issue 502 make the initial parsing of script xml thread safe

---

gui/src/main/java/org/cristalise/gui/tabs/CollectionPane.java
gui/src/main/java/org/cristalise/gui/tabs/DomainPathAdmin.java
gui/src/main/java/org/cristalise/gui/tabs/ExecutionPane.java
gui/src/main/java/org/cristalise/gui/tabs/HistoryPane.java
gui/src/main/java/org/cristalise/gui/tabs/ItemTabPane.java
gui/src/main/java/org/cristalise/gui/tabs/JFixedHeightComboBox.java
gui/src/main/java/org/cristalise/gui/tabs/JTabbedPaneWithCloseIcons.java
gui/src/main/java/org/cristalise/gui/tabs/JobListPane.java
gui/src/main/java/org/cristalise/gui/tabs/PropertiesPane.java
gui/src/main/java/org/cristalise/gui/tabs/RoleAdmin.java
gui/src/main/java/org/cristalise/gui/tabs/ViewpointPane.java
gui/src/main/java/org/cristalise/gui/tabs/WorkflowPane.java
kernel/src/main/java/org/cristalise/kernel/persistency/ClusterStorageManager.java
kernel/src/main/java/org/cristalise/kernel/process/LocalChangeVerticle.java

Issue514 swingui viewpoint refresh bug

---

dev/src/main/groovy/org/cristalise/dev/scaffold/CRUDItemCreator.groovy
dsl/src/main/groovy/org/cristalise/dsl/module/ModuleDelegate.groovy

Issue 516 crud item creator error mode

---

kernel/src/main/java/org/cristalise/kernel/entity/agent/Job.java
kernel/src/main/java/org/cristalise/kernel/entity/proxy/AgentProxy.java
kernel/src/main/java/org/cristalise/kernel/entity/proxy/ItemProxy.java
kernel/src/main/java/org/cristalise/kernel/entity/proxy/ProxyManager.java
kernel/src/main/java/org/cristalise/kernel/entity/proxy/ProxyMessage.java
kernel/src/main/java/org/cristalise/kernel/graph/model/BuiltInVertexProperties.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/Activity.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/predefined/PredefinedStep.java
kernel/src/main/java/org/cristalise/kernel/lookup/ItemPath.java
pom.xml

Issue537 crud update exec predefined step

---

dev/src/main/module/CrudState.groovy
dev/src/main/resources/boot/CA/CrudState_Manage_0.xml
docs/API.md
docs/Events.md
docs/Reference.md
docs/Routing.md
docs/Workflows.md
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/OrSplit.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/Split.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/XOrSplit.java

#548 wildcard and negative match in Alias

---

jooqdb/src/main/java/org/cristalise/storage/jooqdb/JooqClusterStorage.java
jooqdb/src/main/java/org/cristalise/storage/jooqdb/lookup/JooqLookupManager.java
jooqdb/src/test/java/org/cristalise/storage/JooqTransactionTest.java
jooqdb/src/test/java/org/cristalise/storage/jooqdb/JooqClusterStorageTest.java
kernel/src/main/java/org/cristalise/kernel/entity/proxy/ProxyMessage.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/predefined/BulkErase.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/predefined/Erase.java
kernel/src/main/java/org/cristalise/kernel/lookup/SearchFilter.java
kernel/src/main/java/org/cristalise/kernel/persistency/ClusterStorage.java
kernel/src/main/java/org/cristalise/kernel/persistency/ClusterStorageManager.java
kernel/src/main/java/org/cristalise/storage/MemoryOnlyClusterStorage.java
kernel/src/main/java/org/cristalise/storage/XMLClusterStorage.java
lookup-ldap/src/main/java/org/cristalise/lookup/ldap/LDAPClusterStorage.java
testing/src/main/groovy/org/cristalise/restapi/test/BulkEraseTest.groovy
testing/src/main/groovy/org/cristalise/restapi/test/EraseTest.groovy
testing/src/main/groovy/org/cristalise/restapi/test/RestapiTestBase.groovy
testing/src/main/resources/logback-test.xml
xmldb/src/main/java/org/cristalise/storage/xmldb/XMLDBClusterStorage.java

Issue562 BulkErase deletes all items found by the search

---

dsl/src/main/groovy/org/cristalise/dsl/persistency/outcome/DynamicForms.groovy
idl/src/main/java/org/cristalise/kernel/common/GTimeStamp.java
idl/src/main/java/org/cristalise/kernel/common/GTimeStampHelper.java
in-memory-lookup/src/main/groovy/org/cristalise/lookup/lite/InMemoryLookup.groovy
kernel/src/main/java/org/cristalise/kernel/utils/DateUtility.java
kernel/src/main/java/org/cristalise/kernel/utils/GTimeStampComparator.java
kernel/src/main/resources/boot/OD/Errors.xsd
kernel/src/main/resources/mapFiles/HistoryMap.xml
kernel/src/main/resources/mapFiles/KeyValuePairMap.xml
kernel/src/test/data/xmlstorage/directorybased/fcecd4ad-40eb-421c-a648-edc1d74f339b/AuditTrail/0.xml
kernel/src/test/java/org/cristalise/kernel/test/persistency/HistoryTest.java
kernel/src/test/java/org/cristalise/kernel/test/utils/GTimeStampTests.java

#555 added nanosecond to GTimeStamp and DateUtility

---

restapi/src/main/java/org/cristalise/restapi/ItemRoot.java

#531: restapi: Log parameters to help debugging issues

---

dev/src/test/groovy/org/cristalise/kernel/test/lifecycle/instance/CAExecutionSpecs.groovy
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/Activity.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/CompositeActivity.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/WfVertex.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/stateMachine/State.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/stateMachine/Transition.java
kernel/src/main/resources/boot/SM/CompositeActivity.xml

issue571 transition to blocking state is abortable

---

dev/src/test/groovy/org/cristalise/kernel/test/lifecycle/instance/CAExecutionSpecs.groovy
dev/src/test/groovy/org/cristalise/kernel/test/lifecycle/instance/WfInitialiseSpecs.groovy
dev/src/test/resources/logback-test.xml
dsl/src/main/groovy/org/cristalise/dsl/lifecycle/instance/WorkflowBuilder.groovy
dsl/src/main/groovy/org/cristalise/dsl/test/builders/WorkflowTestBuilder.groovy
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/Activity.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/CompositeActivity.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/Join.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/WfVertex.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/stateMachine/StateMachine.java

CompositeActivity is not finished automatically

---

jooqdb/src/main/java/org/cristalise/storage/jooqdb/JooqDataSourceHandler.java

#588: Make source properties configurable

---

dsl/src/main/groovy/org/cristalise/dsl/module/GitStatus.groovy
dsl/src/main/groovy/org/cristalise/dsl/module/IncludeHandler.groovy
dsl/src/main/groovy/org/cristalise/dsl/module/ModuleDelegate.groovy
dsl/src/main/groovy/org/cristalise/dsl/module/ModuleScriptBase.groovy
dsl/src/main/groovy/org/cristalise/dsl/module/ResourceUpdateHandler.groovy
kernel/src/main/java/org/cristalise/kernel/persistency/outcome/Outcome.java

Use GitStatus when including a DSL file

---

webui/README.md
webui/apps/admin/src/app/layout/menu/app.menu.component.ts
webui/libs/core/src/index.ts
webui/libs/core/src/lib/api/logger.ts
webui/libs/core/src/lib/core.module.ts
webui/libs/core/src/lib/services/lookup.service.spec.ts
webui/libs/core/src/lib/services/lookup.service.ts

Issue601 show context tree in menu

---

dev/src/main/module/script/CrudEntity_ChangeDependecy.groovy
dev/src/main/module/script/CrudEntity_ChangeName.groovy
dev/src/main/resources/templates/item_groovy.tmpl
dev/src/test/groovy/org/cristalise/dev/test/scaffold/DevScaffoldedModuleTests.groovy
dev/src/test/module/Car/Car.groovy
dev/src/test/module/ClubMember/ClubMember.groovy
dev/src/test/module/Motorcycle/Motorcycle.groovy
dev/src/test/module/TestAgent/TestAgent.groovy
dev/src/test/module/TestAgentUseConstructor/TestAgentUseConstructor.groovy
dev/src/test/module/TestItem/TestItem.groovy
dev/src/test/module/TestItemGeneratedName/TestItemGeneratedName.groovy
dev/src/test/module/TestItemUseConstructor/TestItemUseConstructor.groovy
dev/src/test/module/TestItemUseConstructorGeneratedName/TestItemUseConstructorGeneratedName.groovy
dev/src/test/resources/org/cristalise/devtest/resources/boot/OD/Car_0.xsd
dev/src/test/resources/org/cristalise/devtest/resources/boot/OD/ClubMember_0.xsd
dev/src/test/resources/org/cristalise/devtest/resources/boot/OD/Motorcycle_0.xsd
dev/src/test/resources/org/cristalise/devtest/resources/boot/OD/TestAgentUseConstructor_0.xsd
dev/src/test/resources/org/cristalise/devtest/resources/boot/OD/TestAgent_0.xsd
dev/src/test/resources/org/cristalise/devtest/resources/boot/OD/TestItemGeneratedName_0.xsd
dev/src/test/resources/org/cristalise/devtest/resources/boot/OD/TestItemUseConstructorGeneratedName_0.xsd
dev/src/test/resources/org/cristalise/devtest/resources/boot/OD/TestItemUseConstructor_0.xsd
dev/src/test/resources/org/cristalise/devtest/resources/boot/OD/TestItem_0.xsd
in-memory-lookup/src/main/groovy/org/cristalise/lookup/lite/InMemoryLookup.groovy
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/Activity.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/predefined/ChangeName.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/predefined/PredefinedStep.java

Auto exec of all predefined step

---

jooqdb/src/main/java/org/cristalise/storage/jooqdb/lookup/JooqLookupManager.java
kernel/src/main/java/org/cristalise/kernel/entity/imports/ImportAgent.java
kernel/src/main/java/org/cristalise/kernel/entity/imports/ImportRole.java
kernel/src/main/java/org/cristalise/kernel/process/Bootstrap.java
kernel/src/main/java/org/cristalise/kernel/process/UserCodeProcess.java

#612: Fix bootstrapping error

---

kernel/src/main/java/org/cristalise/kernel/collection/Aggregation.java
kernel/src/main/java/org/cristalise/kernel/collection/Collection.java
kernel/src/main/java/org/cristalise/kernel/collection/CollectionMemberList.java
kernel/src/main/java/org/cristalise/kernel/collection/Dependency.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/predefined/BulkErase.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/predefined/Erase.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/predefined/ManageMembersOfCollectionBase.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/predefined/PredefinedStep.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/predefined/RemoveMembersFromCollection.java
kernel/src/main/java/org/cristalise/kernel/lifecycle/instance/predefined/agent/RemoveAgent.java
testing/src/main/groovy/org/cristalise/kernel/test/scenario/ItemWithCollectionIT.groovy

Erase triggers RemoveMemberFromCollection

---

dev/pom.xml
dev/src/main/groovy/org/cristalise/dev/dsl/item/CRUDDependency.groovy
dev/src/main/groovy/org/cristalise/dev/dsl/item/CRUDItem.groovy
dev/src/main/groovy/org/cristalise/dev/dsl/module/OpenApiParser.groovy
dev/src/main/groovy/org/cristalise/dev/scaffold/CRUDGenerator.groovy
dev/src/test/groovy/org/cristalise/dev/test/dsl/module/OpenApiParserTest.groovy
kernel/src/main/java/org/cristalise/kernel/utils/DescriptionObject.java

openapi parser

---

dev/pom.xml
pom.xml
restapi/pom.xml

update groovy and vertex dependency

---

pom.xml

update to java release 17

---

jooqdb/src/main/java/org/cristalise/storage/jooqdb/JooqClusterStorage.java
jooqdb/src/main/java/org/cristalise/storage/jooqdb/JooqDataSourceHandler.java
jooqdb/src/main/java/org/cristalise/storage/jooqdb/JooqDomainHandler.java

Call DomainHandler.delete() first

---

.travis.yml
dev/README.md
dev/pom.xml
dev/src/test/resources/org/cristalise/devtest/resources/boot/item/CarFactory_0.xml
dev/src/test/resources/org/cristalise/devtest/resources/boot/item/ClubMemberFactory_0.xml
dev/src/test/resources/org/cristalise/devtest/resources/boot/item/MotorcycleFactory_0.xml
devbox/README-ManualInstall.md
dsl/pom.xml
dsl/src/main/groovy/org/cristalise/dsl/csv/CSVGroovyParser.groovy
in-memory-lookup/pom.xml
jooqdb/pom.xml
pom.xml
testing/pom.xml
testing/src/main/bin/IntegTest restapi.launch
testing/src/main/groovy/org/cristalise/dev/test/scenario/RoutingScriptTest_OrSplitLoop_DevIT.groovy
testing/src/main/groovy/org/cristalise/restapi/Main.groovy
testing/src/main/resources/cluster-config.xml
testing/src/test/resources/cluster-config.xml
testing/src/test/resources/logback-test.xml

Major updates to jdk and all dependencies

---

kernel/src/main/java/org/cristalise/kernel/scripting/Script.java

5.x : Issue #573 Add Script name to warning log
